name: 'Remove Blockmap'
description: 'Removes blockmap release assets'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Delete release assets
      id: delete_assets
      run: |
        IFS=',' read -ra asset_ids <<< "${{ inputs.asset_ids }}"
        for asset_id in "${asset_ids[@]}"; do
          echo "Deleting asset with ID: $asset_id"
          curl -X DELETE -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/kashamalasha/nightscout-widget-electron/releases/assets/$asset_id"
        done
        